### ISSUE TITLE
Incorrect SDCH encoding

### ISSUE THREAD

**Issue by sunnybear** [bacek/sdch_module#10]
Hello. There are a number of bugs in SDCH on-fly encoding. Attached example:
index.html - HTML file
airee.dict - dictionary file (as is)
airee.raw.dict - dictonary file (w/o headers)
index.sdch.html - SDCH-encoded response via sdch_module
[airee.sdch.case.01.zip](https://github.com/yandex/sdch_module/files/603913/airee.sdch.case.01.zip)

open-vcdiff fails to decode encoded response, Google Chrome also fails
\# cat "index.sdch.html" | vcdiff decode -dictionary airee.raw.dict > index.decoded.html
ERROR: Unrecognized VCDIFF format version
Error trying to decode data chunk of length 4637

Nginx SDCH directives:
sdch on:
sdch_dict .../airee.dict;
sdch_url /airee.dict;
sdch_min_length 3096;
sdch_nodict_types text/plain application/xhtml+xml text/richtext text/xsd text/xsl text/xml application/xml application/json image/x-icon application/rss+xml;
sdch_nodict_types text/css;
sdch_nodict_types application/msword application/vnd.ms-excel application/vnd.ms-powerpoint text/csv;
sdch_nodict_types text/javascript application/javascript application/x-javascript text/x-js text/ecmascript application/ecmascript text/vbscript text/fluffscript;
sdch_nodict_types image/vnd.microsoft.icon image/bmp image/x-ms-bmp;
sdch_nodict_types image/svg+xml application/x-font-ttf font/truetype application/x-font font/opentype font/otf font/ttf application/x-font-truetype application/x-font-opentype application/vnd.ms-fontobject application/font-woff application/font-woff2 application/pdf;
sdch_nodict_types application/vnd.groove-tool-template;
sdch_nodict_types image/gif image/png image/jpeg image/tiff;
sdch_disablecv $x_airee_sdch_disablecv;

**Comment by wawaAtYandex** [comment]
I belive the implementation doesn't support the "Format-version" header yet.
Could you please try to remove it for a while?

**Comment by sunnybear** [comment]
The same result. Can you please reproduce this on your environment and debug? Bug is quite stable.

**Comment by wawaAtYandex** [comment]
I need your nginx.confs at least if so.

**Comment by sunnybear** [comment]
user nginx;
pid /var/run/nginx.pid;
events {
    use epoll;
}
http {
    include       /etc/nginx/mime.types;
    charset utf-8;
    server {
        listen 80;
        server_name _;
        location / {
            root /directory;
sdch on;
sdch_dict /directory/airee.dict;
sdch_url /airee.dict;
sdch_min_length 3096;
sdch_nodict_types text/plain application/xhtml+xml text/richtext text/xsd text/xsl text/xml application/xml application/json image/x-icon application/rss+xml;
sdch_nodict_types text/css;
sdch_nodict_types application/msword application/vnd.ms-excel application/vnd.ms-powerpoint text/csv;
sdch_nodict_types text/javascript application/javascript application/x-javascript text/x-js text/ecmascript application/ecmascript text/vbscript text/fluffscript;
sdch_nodict_types image/vnd.microsoft.icon image/bmp image/x-ms-bmp;
sdch_nodict_types image/svg+xml application/x-font-ttf font/truetype application/x-font font/opentype font/otf font/ttf application/x-font-truetype application/x-font-opentype application/vnd.ms-fontobject application/font-woff application/font-woff2 application/pdf;
sdch_nodict_types application/vnd.groove-tool-template;
sdch_nodict_types image/gif image/png image/jpeg image/tiff;
        }
    }
}

**Comment by tejblum** [comment]
It looks like something eaten the beginning of the module output. What version of nginx do you use?

**Comment by sunnybear** [comment]
nginx version: nginx/1.11.6
Will try to re-build nginx with less options to reproduce on 'vanilla' nginx or check modules compatibility.

**Comment by sunnybear** [comment]
Can't confirm :( Rebuilt nginx with new module, retested, the same result (but another sdch-encoded HTML file). The same nginx config. New archive is attached
[airee.sdch.case.01.2016-11-24.zip](https://github.com/yandex/sdch_module/files/611678/airee.sdch.case.01.2016-11-24.zip)

ERROR: Unrecognized VCDIFF format version
Error trying to decode data chunk of length 8733

**Comment by tejblum** [comment]
@sunnybear I think you don't take into account that the SDCH format is not pure VCDIFF-encoding. VCDIFF output is prefixed with the dictionary id and NUL byte, 9 bytes in total. You should skip the prefix before passing the file to the vcdiff  program, e.g. with `tail -c +10` command

**Comment by sunnybear** [comment]
thank you! This works. This issue can be closed.
