### ISSUE TITLE
SDCH support to be removed from Chrome

### ISSUE THREAD

**Issue by redburn** [bacek/sdch_module#11]
It looks like the only browser with SDCH support has now decided to drop it (as of version 59):
> Update: The CL disabling SDCH landed (http://codereview.chromium.org/2785493003) last Friday and has apparently stuck, so we are on track for disabling SDCH in M59.

https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/nQl0ORHy7sw

Hopefully there'll be a new spec, but there doesn't seem to be all that much interest.

I haven't been using SDCH very long, but it certainly helped decrease page load times, so I appreciate the effort you put into creating the sdch_module and helping me troubleshoot some issues here. Thanks!

**Comment by wawaAtYandex** [comment]
It is not the end.
