### ISSUE TITLE
Get-Dictionary header not sent over HTTPS

### ISSUE THREAD

**Issue by redburn** [bacek/sdch_module#5]
Is the module designed to follow the original SDCH spec [[PDF](https://lists.w3.org/Archives/Public/ietf-http-wg/2008JulSep/att-0441/Shared_Dictionary_Compression_over_HTTP.pdf)], which notes that "a request URL falls within a dictionary's scope" when it "is _not_ an HTTPS request"?

The Get-Dictionary header is sent when I configure a virtual host to listen on port 80, and Chrome downloads and stores the dictionary, but as soon as I switch the port to 443 ssl (with or without http2), the Get-Dictionary header is gone. The configuration file is the same except for the listen directive, and of course the directives that apply to SSL.

Most implementations of SDCH I've seen, like Google's and Amazon's, work over HTTPS.

**Comment by bacek** [comment]
Can you provide dump of HTTP and HTTPS requests/response? I suspect you have Avail-Dictionary headers in HTTPS request after initial HTTP roundtrip.

**Comment by redburn** [comment]
I'm testing with different domains for HTTP and HTTPS due to HSTS on the HTTPS domain. The nginx configurations for both hosts are the same except for the listen directive.

**https**://www.example.com (no redirects, no Get-Dictionary, no Avail-Dictionary)

```
GET / HTTP/1.1
Host: www.example.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
```

```
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 21 Aug 2016 08:12:39 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Encoding: gzip
```

**http**://www.example2.com (Avail-Dictionary, dictionary in browser database, sdch encoding)

```
GET /test.html HTTP/1.1
Host: www.example2.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Avail-Dictionary: BCCwbEFb
Accept-Language: en-US,en;q=0.8
```

```
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 21 Aug 2016 08:38:51 GMT
Content-Type: text/html
Last-Modified: Sat, 20 Aug 2016 08:54:43 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Content-Encoding: sdch
Vary: Accept-Encoding, Avail-Dictionary
Content-Encoding: gzip
```

**Comment by bacek** [comment]
You have `Avail-Dictionary` in second request already. Assuming it's the same dictionary server shouldn't issue more `Get-Dictionary` headers.

**Comment by bacek** [comment]
For first one can you give result of simple wget/curl command. Something like this:

```
wget -d --header "Accept-Encoding: gzip, sdch" https://www.example.com
```

**Comment by redburn** [comment]
It looks like "sdch" has to be _last_ in the Accept-Encoding header, or it won't work. Chrome restricts Brotli to HTTPS so that's why it's not included in the Accept-Encoding header for the HTTP domain, making "sdch" the last of the comma-separated values.

These work:
- Accept-Encoding: gzip, deflate, br, sdch
- Accept-Encoding: gzip, deflate, sdch
- Accept-Encoding: gzip, sdch
- Accept-Encoding: sdch

(Server returns Get-Dictionary header)

These don't:
- Accept-Encoding: gzip, deflate, sdch, br
- Accept-Encoding: sdch, gzip
- Accept-Encoding: gzip, sdch, deflate

(Server does not return Get-Dictionary header)

**Comment by bacek** [comment]
Thanks a lot for investigating! Found some strange behaviour in ngx_strstrn and made workaround for it.

**Comment by redburn** [comment]
Great, that fixed it, thanks!
