### ISSUE TITLE
Fastcgi buffers can break SDCH-encoded response

### ISSUE THREAD

**Issue by redburn** [bacek/sdch_module#7]
I was investigating why some FastCGI-powered responses were returning corrupted SDCH-encoded content. It happened with some (but not all) pages that were relatively large (35KB+) in size. This led me to the fastcgi_buffers directive that I had enabled. Disabling it fixed the problem.

I'm guessing that with larger FastCGI responses, the buffer is flushed early to the SDCH module, which then returns a faulty/incomplete SDCH-encoded response to the client. However, as I already mentioned, it didn't happen with all pages, e.g. some 100KB+ pages loaded just fine.

I had them set to:

```
fastcgi_buffers     8 16k;
fastcgi_buffer_size 32k;
```

Any advice would be appreciated.

**Comment by bacek** [comment]
I'm looking at it.

**Comment by bacek** [comment]
Can you build debug version of nginx, switch on debug output and run your test? Then grep lines "fastcgi output out" from debug log. I suspect fastcgi module doesn't always set last_buf flag which breaks sdch's checksum output.

**Comment by redburn** [comment]
Sorry for the delay. Unfortunately, I don't see any log lines similar to "fastcgi output out" in the debug log.

**Comment by bacek** [comment]
Did you build nginx using --with-debug flag in ./configure?

**Comment by redburn** [comment]
I did, but "fastcgi output out" is not part of the [debug] log entries.

**Comment by bacek** [comment]
And you do have something like "error_log /path/to/error.log debug" in your nginx.conf?

**Comment by redburn** [comment]
```
events {
    debug_connection XX.XX.XX.XX;
}
```

Where XX.XX.XX.XX is my IP address. The effect should be the same.

Here's my debug log for a request that fails: [debug.log.txt](https://github.com/yandex/sdch_module/files/478451/debug.log.txt)

**Comment by wawaAtYandex** [comment]
I believe it's a dup for #10.
@redburn, could you please try the patch?

**Comment by redburn** [comment]
Confirmed! Thanks :+1:
