### ISSUE TITLE
ERR_SPDY_PROTOCOL_ERROR with concurrent requests

### ISSUE THREAD

**Issue by redburn** [bacek/sdch_module#8]
Chrome returns ERR_SPDY_PROTOCOL_ERROR when I load an SDCH-enabled URI while another resource is being downloaded in the same session. For example:
- I click on a link to a (large) file and Chrome begins downloading;
- While it's downloading I reload the webpage or click on a link to another webpage;
- Chrome returns ERR_SPDY_PROTOCOL_ERROR.

Requests to resources that are not candidates for SDCH-encoding, such as images, will load just fine. Disabling the sdch_module in the nginx configuration "solves" the issue.

From chrome://net-internals:

> [...]
> t=9753 [st=138]   +HTTP_TRANSACTION_READ_BODY  [dt=1]
> t=9754 [st=139]      HTTP2_STREAM_ERROR
>                      --> description = "SPDY stream closed with status: 6"
>                      --> status = -337
>                      --> stream_id = 67
> t=9754 [st=139]   -HTTP_TRANSACTION_READ_BODY
>                    --> net_error = -337 (ERR_SPDY_PROTOCOL_ERROR)
> t=9754 [st=139]    FAILED
>                    --> net_error = -337 (ERR_SPDY_PROTOCOL_ERROR)
> t=9755 [st=140]    SDCH_DECODING_ERROR
>                    --> net_error = -2 (ERR_FAILED)
>                    --> sdch_problem_code = 95 (PRIOR_TO_DICTIONARY)
> t=9755 [st=140] -REQUEST_ALIVE
>                  --> net_error = -337 (ERR_SPDY_PROTOCOL_ERROR)

I have the nginx debug log enabled, but I'm not sure what to look for.

**Comment by bacek** [comment]
I need more log lines before `t=9753 [st=138] +HTTP_TRANSACTION_READ_BODY [dt=1]` to investigate it.

`PRIOR_TO_DICTIONARY` is emitted by SdchFilter destructor when no data was passed to filter. Looks like something else caused closing of the stream.

**Comment by redburn** [comment]
```
t=5388 [st=  0] +REQUEST_ALIVE  [dt=294]
t=5388 [st=  0]    DELEGATE_INFO  [dt=29]
                   --> delegate_info = "NavigationResourceThrottle"
t=5417 [st= 29]    URL_REQUEST_DELEGATE  [dt=0]
t=5417 [st= 29]    URL_REQUEST_START_JOB  [dt=0]
                   --> load_flags = 37121 (MAIN_FRAME | MAYBE_USER_GESTURE | VALIDATE_CACHE | VERIFY_EV_CERT)
                   --> method = "GET"
                   --> priority = "HIGHEST"
                   --> url = "https://www.example.com"
t=5417 [st= 29]   +URL_REQUEST_START_JOB  [dt=179]
                   --> load_flags = 37121 (MAIN_FRAME | MAYBE_USER_GESTURE | VALIDATE_CACHE | VERIFY_EV_CERT)
                   --> method = "GET"
                   --> priority = "HIGHEST"
                   --> url = "https://www.example.com"
t=5417 [st= 29]      URL_REQUEST_DELEGATE  [dt=0]
t=5417 [st= 29]      HTTP_CACHE_GET_BACKEND  [dt=0]
t=5417 [st= 29]      HTTP_CACHE_OPEN_ENTRY  [dt=1]
                     --> net_error = -2 (ERR_FAILED)
t=5418 [st= 30]      HTTP_CACHE_CREATE_ENTRY  [dt=0]
t=5418 [st= 30]      HTTP_CACHE_ADD_TO_ENTRY  [dt=0]
t=5418 [st= 30]      URL_REQUEST_DELEGATE  [dt=0]
t=5418 [st= 30]     +HTTP_STREAM_REQUEST  [dt=0]
t=5418 [st= 30]        HTTP_STREAM_REQUEST_STARTED_JOB
                       --> source_dependency = 250587 (HTTP_STREAM_JOB)
t=5418 [st= 30]        HTTP_STREAM_REQUEST_BOUND_TO_JOB
                       --> source_dependency = 250587 (HTTP_STREAM_JOB)
t=5418 [st= 30]     -HTTP_STREAM_REQUEST
t=5418 [st= 30]     +HTTP_TRANSACTION_SEND_REQUEST  [dt=0]
t=5418 [st= 30]        HTTP_TRANSACTION_HTTP2_SEND_REQUEST_HEADERS
                       --> :authority: www.example.com
                           :method: GET
                           :path: /
                           :scheme: https
                           accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
                           accept-encoding: gzip, deflate, sdch, br
                           accept-language: en-US,en;q=0.8
                           avail-dictionary: s4sOwtgj
                           cache-control: max-age=0
                           cookie: [381 bytes were stripped]
                           referer: https://www.example.com
                           upgrade-insecure-requests: 1
                           user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
t=5418 [st= 30]     -HTTP_TRANSACTION_SEND_REQUEST
t=5418 [st= 30]     +HTTP_TRANSACTION_READ_HEADERS  [dt=178]
t=5596 [st=208]        HTTP_TRANSACTION_READ_RESPONSE_HEADERS
                       --> HTTP/1.1 200
                           status: 200
                           date: Sat, 17 Sep 2016 22:51:25 GMT
                           content-type: text/html; charset=UTF-8
                           expires: -1
                           cache-control: no-store, no-cache, must-revalidate
                           pragma: no-cache
                           content-encoding: sdch
                           content-encoding: br
                           vary: Accept-Encoding, Avail-Dictionary
t=5596 [st=208]     -HTTP_TRANSACTION_READ_HEADERS
t=5596 [st=208]      HTTP_CACHE_WRITE_INFO  [dt=0]
t=5596 [st=208]      URL_REQUEST_DELEGATE  [dt=0]
t=5596 [st=208]      URL_REQUEST_FILTERS_SET
                     --> filters = "FILTER_TYPE_BROTLI,FILTER_TYPE_SDCH"
t=5596 [st=208]   -URL_REQUEST_START_JOB
t=5596 [st=208]   +URL_REQUEST_DELEGATE  [dt=1]
t=5596 [st=208]      DELEGATE_INFO  [dt=0]
                     --> delegate_info = "NavigationResourceThrottle"
t=5597 [st=209]   -URL_REQUEST_DELEGATE
t=5597 [st=209]   +HTTP_TRANSACTION_READ_BODY  [dt=84]
t=5681 [st=293]      HTTP2_STREAM_ERROR
                     --> description = "SPDY stream closed with status: 6"
                     --> status = -337
                     --> stream_id = 1505
t=5681 [st=293]   -HTTP_TRANSACTION_READ_BODY
                   --> net_error = -337 (ERR_SPDY_PROTOCOL_ERROR)
t=5681 [st=293]    FAILED
                   --> net_error = -337 (ERR_SPDY_PROTOCOL_ERROR)
t=5682 [st=294]    SDCH_DECODING_ERROR
                   --> net_error = -2 (ERR_FAILED)
                   --> sdch_problem_code = 95 (PRIOR_TO_DICTIONARY)
t=5682 [st=294] -REQUEST_ALIVE
                 --> net_error = -337 (ERR_SPDY_PROTOCOL_ERROR)
```

**Comment by bacek** [comment]
Can you try to disable mod_brotli? Just to make sure that is not
inter-filter breakage?

**Comment by redburn** [comment]
Same result with mod_brotli disabled. Also tried disabling gzip (though I applied the patch).

**Comment by tonytranupc** [comment]
Sometimes, it isn't an error from the server side. I've encountered this type of error several times before and in most cases, it was a fault from my computer.

I think [this tutorial](https://usefulpcguide.com/18302/fix-err_spdy_protocol_error-google-chrome/) might help you to fix ERR_SPDY_PROTOCOL_ERROR.

**Comment by redburn** [comment]
When you can toggle the behavior by enabling/disabling the sdch_module, it's not a "computer" issue.

**Comment by wawaAtYandex** [comment]
Have you tried last revision of the module?

**Comment by redburn** [comment]
I have, yes. #7 is fixed, but this issue remains.

**Comment by wawaAtYandex** [comment]
May I see the chrome://net-internals#sdch ?

**Comment by redburn** [comment]
Anything in particular? I'm attaching a screenshot of the SDCH panel. 

(Domain changed to example.com.)

![screen shot 2016-11-25 at 23 28 07](https://cloud.githubusercontent.com/assets/3878542/20636088/e061af84-b366-11e6-9230-35826422b2fb.png)

**Comment by redburn** [comment]
Can anyone who uses the sdch_module reproduce this issue? Basically, you download a large file from the server and try to open an SDCH-encoded resource while the browser is still downloading that file. I serve a lot of large files, and this means users cannot continue browsing the site while downloading.

**Comment by wawaAtYandex** [comment]
I've found the bug.
Will back w/patch soon.

**Comment by wawaAtYandex** [comment]
I believe the issue has been fixed.
Could you please confirm it is in your environment?

**Comment by redburn** [comment]
Confirmed! Sorry for the delay, and thanks for fixing the issue.
